name: Check Stacked

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  fail-if-stacked:
    if: contains(github.event.pull_request.labels.*.name, 'stacked')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is stacked on another branch.
        run: |
          echo "This PR is currently stacked."
          exit 1
